export const SERVICES = {
  ACCOUNTS: "ACCOUNTS_SERVICE",
  QUEUE: "QUEUE_SERVICE",
  NOTIFICATION: "NOTIFICATION_SERVICE",
  ANALYTICS: "ANALYTICS_SERVICE",
  TELEGRAM: "TELEGRAM_SERVICE",
  WEBSOCKET: "WEBSOCKET_SERVICE",
} as const;

export const SERVICE_PORTS = {
  GATEWAY: 5000,
  ACCOUNTS: 5001,
  QUEUE: 5002,
  NOTIFICATION: 5003,
  ANALYTICS: 5004,
  TELEGRAM: 5005,
  WEBSOCKET: 5006,
} as const;
