export enum TicketEventType {
  CREATED = "CREATED",
  ENTERED_QUEUE = "ENTERED_QUEUE",
  CALLED = "CALLED",
  SERVING_STARTED = "SERVING_STARTED",
  COMPLETED = "COMPLETED",
  SKIPPED = "SKIPPED",
  RECALLED = "RECALLED",
  TRANSFERRED = "TRANSFERRED",
}
